version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d foodgram"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: a1go3/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: a1go3/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: a1go3/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 9000:80
    depends_on:
      - backend