# Generated by Django 3.2.3 on 2023-08-02 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food.IngredientAmount', to='food.Ingredient', validators=[django.core.validators.MinValueValidator(1, message='Добавьте хотя бы один ингредиент')], verbose_name='Ингредиент'),
        ),
    ]
