# Generated by Django 3.2.3 on 2023-08-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20230802_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food.IngredientAmount', to='food.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
