# Generated by Django 3.2.3 on 2023-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
    ]
